import { PERMS_ACCESS_HOME_PAGE } from './common';

export const PERMS_ADMIN_LOGIN = 'PERMS_ADMIN_LOGIN';

export const PERMS_ADMIN_LOGOUT = 'PERMS_ADMIN_LOGOUT';

export const PERMS_ADMIN_UPDATE = 'PERMS_ADMIN_UPDATE';

export const PERMS_ADD_USER_PERMISSION = 'PERMS_ADD_USER_PERMISSION';

export const PERMS_REMOVE_USER_PERMISSION = 'PERMS_REMOVE_USER_PERMISSION';

//
export const PERMS_CREATE_OPTION = 'PERMS_CREATE_OPTION';

export const PERMS_DELETE_OPTION = 'PERMS_DELETE_OPTION';

export const PERMS_UPDATE_OPTION = 'PERMS_UPDATE_OPTION';

export const PERMS_GET_OPTION = 'PERMS_GET_OPTION';

export const PERMS_FIND_OPTION = 'PERMS_FIND_OPTION';

//
export const PERMS_FIND_OPTION_ALL = 'PERMS_FIND_OPTION_ALL';

export const PERMS_CREATE_CATEGORY = 'PERMS_CREATE_CATEGORY';

export const PERMS_DELETE_CATEGORY = 'PERMS_DELETE_CATEGORY';

export const PERMS_UPDATE_CATEGORY = 'PERMS_UPDATE_CATEGORY';

export const PERMS_GET_CATEGORY = 'PERMS_GET_CATEGORY';

export const PERMS_FIND_CATEGORY = 'PERMS_FIND_CATEGORY';

//
export const PERMS_CREATE_FAMILY = 'PERMS_CREATE_FAMILY';

export const PERMS_DELETE_FAMILY = 'PERMS_DELETE_FAMILY';

export const PERMS_UPDATE_FAMILY = 'PERMS_UPDATE_FAMILY';

export const PERMS_GET_FAMILY = 'PERMS_GET_FAMILY';

export const PERMS_FIND_FAMILY = 'PERMS_FIND_FAMILY';

export const PERMS_FIND_FAMILY_ALL = 'PERMS_FIND_FAMILY_ALL';

//
export const PERMS_CREATE_STORE = 'PERMS_CREATE_STORE';

export const PERMS_DELETE_STORE = 'PERMS_DELETE_STORE';

export const PERMS_UPDATE_STORE = 'PERMS_UPDATE_STORE';

export const PERMS_GET_STORE = 'PERMS_GET_STORE';

export const PERMS_FIND_STORE = 'PERMS_FIND_STORE';

export const PERMS_FIND_STORE_ALL = 'PERMS_FIND_STORE_ALL';

export const PERMS_ADD_STORE_WYS = 'PERMS_ADD_STORE_WYS';

export const PERMS_REMOVE_STORE_WYS = 'PERMS_REMOVE_STORE_WYS';

//
export const PERMS_REMOVE_SHOPKEEPER_PERMISSION =
  'PERMS_REMOVE_SHOPKEEPER_PERMISSION';

export const PERMS_ADD_SHOPKEEPER_PERMISSION =
  'PERMS_ADD_SHOPKEEPER_PERMISSION';
//
export const PERMS_FIND_CART = 'PERMS_FIND_CART';

export const ADMIN_DEFAULT_PERMISSIONS = {
  PERMS_ADMIN_LOGIN,
  PERMS_ADMIN_LOGOUT,
  PERMS_ACCESS_HOME_PAGE,
  PERMS_ADD_USER_PERMISSION,
  PERMS_REMOVE_USER_PERMISSION,
  PERMS_CREATE_OPTION,
  PERMS_DELETE_OPTION,
  PERMS_UPDATE_OPTION,
  PERMS_GET_OPTION,
  PERMS_FIND_OPTION,
  PERMS_CREATE_CATEGORY,
  PERMS_DELETE_CATEGORY,
  PERMS_UPDATE_CATEGORY,
  PERMS_GET_CATEGORY,
  PERMS_FIND_CATEGORY,
  PERMS_FIND_OPTION_ALL,
  PERMS_CREATE_FAMILY,
  PERMS_DELETE_FAMILY,
  PERMS_UPDATE_FAMILY,
  PERMS_GET_FAMILY,
  PERMS_FIND_FAMILY,
  PERMS_FIND_FAMILY_ALL,
  PERMS_CREATE_STORE,
  PERMS_UPDATE_STORE,
  PERMS_DELETE_STORE,
  PERMS_GET_STORE,
  PERMS_FIND_STORE,
  PERMS_FIND_STORE_ALL,
  PERMS_ADD_STORE_WYS,
  PERMS_REMOVE_STORE_WYS,
  PERMS_REMOVE_SHOPKEEPER_PERMISSION,
  PERMS_ADD_SHOPKEEPER_PERMISSION,
  PERMS_FIND_CART,
};
