export const PERMS_DELETE_SHOPKEEPER = 'PERMS_DELETE_SHOPKEEPER';

export const PERMS_FIND_ALL_SHOPKEEPER = 'PERMS_FIND_ALL_SHOPKEEPER';

export const PERMS_ADD_PERMS_SHOPKEEPER = 'PERMS_ADD_PERMS_SHOPKEEPER';

//
export const PERMS_DELETE_PRODUCT = 'PERMS_DELETE_PRODUCT';

export const PERMS_UPDATE_PRODUCT = 'PERMS_UPDATE_PRODUCT';

export const PERMS_CREATE_PRODUCT = 'PERMS_CREATE_PRODUCT';

export const PERMS_ADD_PRODUCT_OPTION = 'PERMS_ADD_PRODUCT_OPTION';

export const PERMS_REMOVE_PRODUCT_OPTION = 'PERMS_REMOVE_PRODUCT_OPTION';

export const PERMS_UPDATE_PRODUCT_OPTION = 'PERMS_UPDATE_PRODUCT_OPTION';
//
export const PERMS_DELETE_VARIATION = 'PERMS_DELETE_PRODUCT';

export const PERMS_UPDATE_VARIATION = 'PERMS_UPDATE_PRODUCT';

export const PERMS_CREATE_VARIATION = 'PERMS_CREATE_PRODUCT';

export const PERMS_ADD_VARIATION_OPTION = 'PERMS_ADD_PRODUCT_OPTION';

export const PERMS_REMOVE_VARIATION_OPTION = 'PERMS_REMOVE_PRODUCT_OPTION';

export const PERMS_UPDATE_VARIATION_OPTION = 'PERMS_UPDATE_PRODUCT_OPTION';
//
export const PERMS_ADD_IMAGE = 'PERMS_ADD_IMAGE';

export const PERMS_REMOVE_IMAGE = 'PERMS_REMOVE_IMAGE';

export const PERMS_SET_FEATURED_IMAGE = 'PERMS_SET_FEATURED_IMAGE';

export const PERMS_SET_FEATURED_VIDEO = 'PERMS_SET_FEATURED_VIDEO';
//
export const PERMS_ADD_STORE_IMAGE = 'PERMS_ADD_STORE_IMAGE';

export const SHOPKEEPER_DEFAULT_PERMS = {
  PERMS_DELETE_SHOPKEEPER,
  PERMS_FIND_ALL_SHOPKEEPER,
  PERMS_ADD_PERMS_SHOPKEEPER,
  PERMS_DELETE_PRODUCT,
  PERMS_UPDATE_PRODUCT,
  PERMS_CREATE_PRODUCT,
  PERMS_ADD_PRODUCT_OPTION,
  PERMS_REMOVE_PRODUCT_OPTION,
  PERMS_UPDATE_PRODUCT_OPTION,
  PERMS_DELETE_VARIATION,
  PERMS_UPDATE_VARIATION,
  PERMS_CREATE_VARIATION,
  PERMS_ADD_VARIATION_OPTION,
  PERMS_REMOVE_VARIATION_OPTION,
  PERMS_UPDATE_VARIATION_OPTION,
  PERMS_ADD_IMAGE,
  PERMS_REMOVE_IMAGE,
  PERMS_SET_FEATURED_IMAGE,
  PERMS_SET_FEATURED_VIDEO,
  PERMS_ADD_STORE_IMAGE,
};
