import { PERMS_ACCESS_HOME_PAGE } from './common';

export const PERMS_USER_LOGIN = 'PERMS_USER_LOGIN';

export const PERMS_USER_LOGOUT = 'PERMS_USER_LOGOUT';

export const PERMS_OPEN_STORE = 'PERMS_OPEN_STORE';

export const PERMS_CREATE_SHOPKEEPER = 'PERMS_CREATE_SHOPKEEPER';

export const PERMS_ADD_PRODUCT_TO_CART = 'PERMS_ADD_PRODUCT_TO_CART';

export const PERMS_REMOVE_PRODUCT_TO_CART = 'PERMS_REMOVE_PRODUCT_TO_CART';

export const PERMS_USER_SUBSCRIBE = 'PERMS_USER_SUBSCRIBE';

export const PERMS_USER_UNSUBSCRIBE = 'PERMS_USER_UNSUBSCRIBE';

export const USER_DEFAULTS_PERMISSIONS = {
  PERMS_USER_LOGOUT,
  PERMS_USER_LOGIN,
  PERMS_ACCESS_HOME_PAGE,
  PERMS_OPEN_STORE,
  PERMS_CREATE_SHOPKEEPER,
  PERMS_ADD_PRODUCT_TO_CART,
  PERMS_REMOVE_PRODUCT_TO_CART,
  PERMS_USER_SUBSCRIBE,
  PERMS_USER_UNSUBSCRIBE,
};
