version: '3.9'
services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - marketplace
    ports:
      - '5000:5000'
    env_file:
      - ./app.env
    depends_on:
      mongo:
        condition: service_started
    volumes:
      - ./:/app:rw
      - /app/node_modules
    restart: always
    command: yarn run dev
  mongo:
    image: mongo
    networks:
      - marketplace
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: jude
      MONGO_INITDB_ROOT_PASSWORD: p9Y38w01811GjH8QXm
      MONGO_INITDB_DATABASE: marketplace
    volumes:
      - ./db:/data/db/
networks:
  marketplace:
