# This compose file is for demonstration only, do not use in prod.
version: '3.3'
services:
  logto:
    depends_on:
      postgres:
        condition: service_healthy
    image: svhd/logto:prerelease
    ports:
      - 3001:3001
    environment:
      - ALL_YES=1
      - NO_INQUIRY=0
      - TRUST_PROXY_HEADER=1
      - DB_URL_DEFAULT=postgres://postgres:p0stgr3s@postgres:5432
      - ENDPOINT
  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    expose:
      - 5000
    env_file:
      - ./app.env
    depends_on:
      mongo:
        condition: service_started
    volumes:
      - ./:/app:rw
      - /app/node_modules
    restart: always
    command: yarn run dev
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: jude
      MONGO_INITDB_ROOT_PASSWORD: p9Y38w01811GjH8QXm
      MONGO_INITDB_DATABASE: marketplace
